"""empty message

Revision ID: 04c31732b457
Revises: 17eb5f7cae5e
Create Date: 2022-02-06 09:22:27.587047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c31732b457'
down_revision = '17eb5f7cae5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'num_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('num_words', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
