"""empty message

Revision ID: 0b4b50a59dd3
Revises: ed2a592382bc
Create Date: 2022-02-20 07:49:29.186334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4b50a59dd3'
down_revision = 'ed2a592382bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vote', 'game', ['game_id'], ['game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_column('vote', 'game_id')
    # ### end Alembic commands ###
