"""empty message

Revision ID: 36484b145695
Revises: 91066d38d411
Create Date: 2022-02-08 08:23:40.195318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36484b145695'
down_revision = '91066d38d411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'definition', 'game', ['game_id'], ['game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'definition', type_='foreignkey')
    op.drop_column('definition', 'game_id')
    # ### end Alembic commands ###
