"""empty message

Revision ID: 91066d38d411
Revises: 04c31732b457
Create Date: 2022-02-06 09:40:40.282656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91066d38d411'
down_revision = '04c31732b457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definition',
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('is_def', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.word_id'], ),
    sa.PrimaryKeyConstraint('definition_id')
    )
    op.drop_table('defintion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defintion',
    sa.Column('definition_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_def', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], name='defintion_player_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['word.word_id'], name='defintion_word_id_fkey'),
    sa.PrimaryKeyConstraint('definition_id', name='defintion_pkey')
    )
    op.drop_table('definition')
    # ### end Alembic commands ###
