"""empty message

Revision ID: ed2a592382bc
Revises: 36484b145695
Create Date: 2022-02-15 21:07:12.007216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2a592382bc'
down_revision = '36484b145695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('voter', sa.Integer(), nullable=True),
    sa.Column('vote_receiver', sa.Integer(), nullable=True),
    sa.Column('definition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['definition.definition_id'], ),
    sa.ForeignKeyConstraint(['vote_receiver'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['voter'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
